<a href="https://colab.research.google.com/github/tdeepakb/Deepak_Python_project/blob/master/Model_4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Assignment-1

1. Create a list named ‘myList’ that has the following elements: 10, 20, 30,
‘apple’, True, 8.10:
a. Now in the ‘myList’, append these values: 30, 40
b. After that, reverse the elements of the ‘myList’ and store that in
‘reversedList

In [ ]:
my_list = [10,20,30,'apple',True,8.10]

In [ ]:
my_list.append(30)

In [ ]:
my_list.append(40)

In [ ]:
my_list

[10, 20, 30, 'apple', True, 8.1, 30, 40]

In [ ]:
reversed_List = my_list[::-1]

In [ ]:
print(reversed_List)

[40, 30, 8.1, True, 'apple', 30, 20, 10]


2. Create a dictionary with key values as 1, 2, 3 and the values as ‘data’,
‘information’ and ‘text’:
a. After that, eliminate the ‘text’ value from the dictionary
b. Add ‘features’ in the dictionary
c. Fetch the ‘data’ element from the dictionary and display it in the output

In [ ]:
dict = {
    'key': 'values',
    '1': 'data',
    '2': 'information',
    '3': 'text'
}
print(dict)

{'key': 'values', '1': 'data', '2': 'information', '3': 'text'}


In [ ]:
del dict['3']

In [ ]:
print(dict)

{'key': 'values', '1': 'data', '2': 'information'}


In [ ]:
dict['features'] = 'new_features'

In [ ]:
print(dict)

{'key': 'values', '1': 'data', '2': 'information', 'features': 'new_features'}


In [ ]:
print(dict['key'])
print(dict['1'])
print(dict['2'])
print(dict['features'])

values
data
information
new_features


3. Create a tuple and add these elements 1, 2, 3, apple, mango in my_tuple.

In [ ]:
my_tuple = (1,2,3,'apple','mango')
print(my_tuple)

(1, 2, 3, 'apple', 'mango')


4. Create another tuple named numeric_tuple consisting of only integer
values 10, 20, 30, 40, 50:

a. Find the minimum value from the numeric_tuple
b. Concatenate my_tuple with numeric_tuple and store the result in r1
c. Duplicate the tuple named my_tuple 2 times and store that in ‘newdupli’

In [ ]:
numeric_tuple = (10,20,30,40,50)
print(numeric_tuple)

(10, 20, 30, 40, 50)


In [ ]:
min(numeric_tuple)

10

In [ ]:
print(my_tuple)
print(numeric_tuple)

(1, 2, 3, 'apple', 'mango')
(10, 20, 30, 40, 50)


In [ ]:
# concenate my_tuple & numeric_tuple
r1 = my_tuple+numeric_tuple
r1

(1, 2, 3, 'apple', 'mango', 10, 20, 30, 40, 50)

In [25]:
my_dupli= my_tuple * 2
my_dupli

(1, 2, 3, 'apple', 'mango', 1, 2, 3, 'apple', 'mango')

5. Create 2 sets with the names set1 and set2, where set1 contains
{1,2,3,4,5} and set2 contains {2,3,7,6,1}
Perform the below operation:
a. set1 union set2
b. set1 intersection set2
c. set1 difference set2

In [26]:
set1 = {1,2,3,4,5}
set2 = {2,3,7,6,1}

In [28]:
set_union = set1.union(set2)
set_union

{1, 2, 3, 4, 5, 6, 7}

In [29]:
set_inter = set1.intersection(set2)
set_inter

{1, 2, 3}

In [30]:
set_diff = set1.difference(set2)
set_diff

{4, 5}

Assignment- 2

1. Create a 3x3 matrix array with values ranging from 2 to 10.
2. Create a NumPy array having user input values and convert the integer
type to the float type of the elements of the array. For instance: Original
array [1, 2, 3, 4] Array converted to a float type: [ 1. 2. 3. 4.]
3. Write a NumPy program to append values to the end of an array. For
instance: Original array: [10, 20, 30] . After that, append values to the end
of the array: [10 20 30 40 50 60 70 80 90]
4. Create two NumPy arrays and add the elements of both the arrays and
store the result in sumArray.
5. Create a 3x3 array having values from 10-90 (interval of 10) and store that
in array1
Perform the following tasks:
a. Extract the 1st row from the array
b. Extract the last element from the array

In [31]:
import numpy as np

In [32]:
x = np.arange(2,11).reshape(3,3)
x

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [42]:
ar1 = np.array([1,2,3,4])

In [43]:
ar1

array([1, 2, 3, 4])

In [44]:
flt = ar1.astype(float)
flt

array([1., 2., 3., 4.])

In [46]:
arr1 = np.array([10,20,30])
arr2 = np.array([40,50,60,70,80,90])
result= np.hstack((arr1,arr2))
result

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [48]:
ar1 = np.array([2,3,4,5,6])
ar2 = np.array([9,8,7,6,5])
sumarr= np.add(ar1,ar2)
sumarr

array([11, 11, 11, 11, 11])

In [53]:
array1 = np.arange(10, 100, 10).reshape(3, 3)
array1

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [54]:
array1[0]

array([10, 20, 30])

In [56]:
array1[2]

array([70, 80, 90])